version: '3.8'

services:

    web:
       image: nginx:stable-alpine
       ports:
           - 80:80
           - 443:443
       container_name: nginx_web
       volumes: 
           - ./app:/var/www/html
           - ./nginx.conf:/etc/nginx/nginx.conf
       depends_on:
           - app
          
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony_app
        volumes:
            - ./app:/var/www/html
        environment:
            - APP_ENV=dev
        working_dir: /var/www/html
        depends_on:
            - db
        tty: true
   
    db:
      image: mysql:latest
      container_name: mysql_db
      volumes:
          - db_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony

    mailcatcher:
      image: schickling/mailcatcher
      container_name: mailcatcher
      ports:
          - "1080:1080"
          
volumes:
    db_data:
       driver: local
